#ifndef PICATTENDANCEPHPEXTENSION_CROP_IMAGE_H
#define PICATTENDANCEPHPEXTENSION_CROP_IMAGE_H

#include "phpcpp.h"

Php::Value CropImage(Php::Parameters& parameters);

#endif // PICATTENDANCEPHPEXTENSION_CROP_IMAGE_H
